compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

name = "tisdagsgolfen-astro"
pages_build_output_dir = "./dist"

[vars]
USER_PASSWORD = 'password'
NODE_VERSION = '24.0.1'

[[d1_databases]]
binding = "DB"
database_name = "tisdagsgolfen-prod-db"
database_id = "6f0c2a6c-0965-4c76-bbb1-008e160199ba"
preview_database_id = "DB"
migrations_dir  = "./src/db/_drizzle"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "tisdagsgolfen-preview-db"
database_id = "322c64a3-fe96-47dd-abd9-ff1f3c3c5054"
migrations_dir  = "./src/db/_drizzle"

[[kv_namespaces]]
binding = "SESSION"
id = "4f4c5168780e4d23a5bfa7940642c82a"
